### ISSUE TITLE
ReferenceError: msg is not defined

### ISSUE THREAD

**Issue by RohitJ1995** [jverce/salesforce-webhooks#8]
Hi
Looks like it should be error.msg
https://github.com/jverce/salesforce-webhooks/blob/9bc4a7e7ea43683b2d1de31e1e83b317f9bafb53/src/client.js#L174
https://github.com/jverce/salesforce-webhooks/blob/9bc4a7e7ea43683b2d1de31e1e83b317f9bafb53/src/client.js#L227
this is resulting in ReferenceError

**Comment by jverce** [comment]
Solved in  #6
